### ISSUE TITLE
Android Open Project Collection

### ISSUE THREAD

**Issue by Trinea** [Trinea/android-open-project#1]
欢迎大家推荐好的Android开源项目，请直接[Commit](https://github.com/Trinea/android-open-project/wiki)，而不要在这里留言

**Comment by ogaclejapan** [comment]
I has released two library. 

A custom ViewPager title strip
https://github.com/ogaclejapan/SmartTabLayout

A very simple arc layout library for Android
https://github.com/ogaclejapan/ArcLayout

**Comment by kingideayou** [comment]
1.TagCloudView(支持 SingleLine 模式的标签云)  
标签云效果，只需要一行代码即可设置为 SingleLine 模式，轻松实现知乎问题话题列表效果  
项目地址：[https://github.com/kingideayou/TagCloudView](https://github.com/kingideayou/TagCloudView)  
示例APK地址：[https://github.com/kingideayou/TagCloudView/raw/master/apk/Demo.apk](https://github.com/kingideayou/TagCloudView/raw/master/apk/Demo.apk)  
APP示例：知乎  
效果图：  
![Renderings](https://raw.githubusercontent.com/kingideayou/TagCloudView/master/imgs/tagCloudView_1.png)  
![Renderings](https://raw.githubusercontent.com/kingideayou/TagCloudView/master/imgs/tagCloudView_2.png)   
![Renderings](https://raw.githubusercontent.com/kingideayou/TagCloudView/master/imgs/tagCloudView_3.gif)
