### ISSUE TITLE
关于该的项目建议

### ISSUE THREAD

**Issue by motcwang** [Trinea/android-open-project#158]
现在这里收集的开源项目越来越多了，是不是该过滤一些，就是说有个对比，在效果相同的项目中，留下实现好、扩展性好、思路好的一些开源项目。纯个人想法

**Comment by chronoswb** [comment]
赞同，这也为查阅的新人提供方便，不然相同功能的项目也不知道选哪个好

**Comment by bunnyblue** [comment]
怎么评估

**Comment by motcwang** [comment]
这个就需要去分析这些项目，然后提出来，如果好，好在哪，要指明

**Comment by Trinea** [comment]
为了不干扰这个项目近二千的 Watcher，关于这个项目的建议请大家移步到 [Android 开源汇总项目改版意见收集](http://codekk.com/blogs/detail/Trinea/Android%20%E5%BC%80%E6%BA%90%E6%B1%87%E6%80%BB%E9%A1%B9%E7%9B%AE%E6%94%B9%E7%89%88%E6%84%8F%E8%A7%81%E6%94%B6%E9%9B%86) 讨论
