### ISSUE TITLE
maps section: tools for location based apps

### ISSUE THREAD

**Issue by karussell** [Trinea/android-open-project#166]
I would introduce a new maps section and add the following open source projects:
 * [mapsforge](https://github.com/mapsforge/mapsforge/) offline vector maps
 * [graphhopper](https://github.com/graphhopper/graphhopper/) a routing engine

based on OpenStreetMap data

**Comment by Trinea** [comment]
You can pull request direct like https://github.com/Trinea/android-open-project/wiki

**Comment by karussell** [comment]
Sorry. Is it sufficient to create a pull request with a change to the english version?

**Comment by Trinea** [comment]
Yes
