### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by jtyang** [Trinea/android-open-project#185]
1.32后面的序号排错了；
2. ExplorerView 文件浏览器，------------》这个开源库的链接搞错了。

**Comment by pcqpcq** [comment]
你可以直接修改的，然后提交pr --> Pull Request

**Comment by ChoingHyun** [comment]
Cards-UI
卡片式 View，支持单个卡片，item 为卡片的 ListView
项目地址：https://github.com/afollestad/Cards-UI
Demo 地址：https://github.com/Trinea/TrineaDownload/blob/master/cards-ui-demo.apk?raw=true

链接失效
