### ISSUE TITLE
建议重新整理下项目

### ISSUE THREAD

**Issue by demonyan** [Trinea/android-open-project#207]
>1. 看到满屏的项目好有压力啊，感觉弄成[Android官方培训课程中文版](http://hukai.me/android-training-course-in-chinese/index.html)这样会好一些
>2. 项目多且杂，2000多行中不容易找到理想的项目。感觉可以根据star数或者项目质量排序要好点

*纯属个人意见！*

**Comment by Trinea** [comment]
已经迁移到 http://p.codekk.com/
