### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by xxzj990** [Trinea/android-open-project#225]
提个建议，望采纳。

主页太大了，能用WiKi进行分页就更好了:)

**Comment by Trinea** [comment]
已经改到 http://p.codekk.com/

**Comment by Vurtex** [comment]
页面好像打不开了，需要翻墙吗？

**Comment by Trinea** [comment]
最近在迁移服务器，codekk.com 暂时不可访问，大家可通过 http://p.wugengxin.cn/ 访问
