### ISSUE TITLE
SwipeListView 项目已被删除

### ISSUE THREAD

**Issue by MummyDing** [Trinea/android-open-project#232]
ListView部分中第5个项目SwipeListView 的项目地址 https://github.com/47deg/android-swipelistview
失效,我在https://github.com/47deg 中也没有找到,该项目应该是被移除了.

**Comment by htrim87** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

htrim87@naver.com 님께 보내신 메일 <[android-open-project] SwipeListView 项目已被删除 (#232)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by laucherish** [comment]
现在基本都使用RecyclerView了吧。
