### ISSUE TITLE
感觉首页都快溢出了！

### ISSUE THREAD

**Issue by laucherish** [Trinea/android-open-project#264]
话说首页为什么可以这么长呢？

**Comment by Trinea** [comment]
首页已经不再维护，最新可搜索版见：http://p.codekk.com/

**Comment by sandy1108** [comment]
感觉可以用githubpages来搞，感觉挺不错的。

**Comment by zfbp** [comment]
请把Readme.md中的图片引用都关闭了吧，打开时间实在太长了。

**Comment by jp1017** [comment]
https://github.com/XXApple/AndroidLibs
