### ISSUE TITLE
README.md打开慢

### ISSUE THREAD

**Issue by KevinEnjoy** [Trinea/android-open-project#292]
README.md内容越来越多，打开越来越慢，每次都被加载的图片把页面跳来跳去的，想下办法怎么改进一下？如 25.ListBuddies 的图尺寸也太大了....

**Comment by Trinea** [comment]
这里只 Merge 不再维护。

最新支持搜索、支持自动更新最新库、更好的浏览体验版本请见 [p.codekk.com](http://p.codekk.com)
