### ISSUE TITLE
希望加上这个库

### ISSUE THREAD

**Issue by Xiaofei-it** [Trinea/android-open-project#294]
[HermesEventBus-饿了么开源的Android跨进程事件分发框架](https://elelogistics.github.io/2016/07/13/HermesEventBus-%E4%B8%80%E7%A7%8D%E6%96%B0%E7%9A%84Android%E8%B7%A8%E8%BF%9B%E7%A8%8B%E4%BA%8B%E4%BB%B6%E5%88%86%E5%8F%91%E6%A1%86%E6%9E%B6/)

[HermesEventBus](https://github.com/eleme/HermesEventBus) is a library for using EventBus between processes, useful in IPC or plugin-in development.

**Comment by Trinea** [comment]
可添加到 http://p.codekk.com/ 这里只接受 Merge，不再主动维护。
