### ISSUE TITLE
Readme页面图片太多，导致很多图片加载失败，无法显示

### ISSUE THREAD

**Issue by taolin2107** [Trinea/android-open-project#295]
Readme页面图片太多，导致很多图片加载失败，特别是动图，无法显示，建议按Project类型分类，每个类型的汇总单独用一个页面。

**Comment by GitFuture** [comment]
是的，README.md 的内容太多了，可以把 5 个部分分成 5-6 个 md 文件。README 做个目录。不然直接加载很慢

**Comment by yangqiong** [comment]
一直在加载图片，导致页面不断跳动
