### ISSUE TITLE
把这个大的README.md拆分成几个会不会更好？（Will it be better to split the big 'README.md' file?)

### ISSUE THREAD

**Issue by MuchContact** [Trinea/android-open-project#308]
文件里有很多图片，网速差点，加载很慢，而且位置在不断变化（以为加载图片的原因），所以是不是可以考虑按照一定结构拆分成几个小文件。

**Comment by Trinea** [comment]
拆分后跟现在类似，同样不能很好的解决搜索、自动新增项目、自动维护这些更重要的问题。

这个项目已经有了更合适的网页版：http://p.codekk.com/
