### ISSUE TITLE
2017 各大公司 Android 内推

### ISSUE THREAD

**Issue by Trinea** [Trinea/android-open-project#318]
2017 年各大公司 Android 内推职位已经做了最新的整理，希望能在整体市场冷清同时 Android 又严重饱和的情况下为大家跳槽提供更合适的渠道。

今年内推职位包括：
北京：[阿里](http://www.trinea.cn/android/%E9%98%BF%E9%87%8C%E9%9B%86%E5%9B%A2%E3%80%81%E8%9A%82%E8%9A%81%E9%87%91%E6%9C%8D%E5%8C%97%E4%B8%8A%E5%B9%BF%E6%B7%B1%E6%9D%AD%E6%8B%9B%E8%81%98-android-ios-%E5%B7%A5%E7%A8%8B%E5%B8%88%E3%80%81/)、腾讯、[蚂蚁金服](http://www.trinea.cn/android/%E9%98%BF%E9%87%8C%E9%9B%86%E5%9B%A2%E3%80%81%E8%9A%82%E8%9A%81%E9%87%91%E6%9C%8D%E5%8C%97%E4%B8%8A%E5%B9%BF%E6%B7%B1%E6%9D%AD%E6%8B%9B%E8%81%98-android-ios-%E5%B7%A5%E7%A8%8B%E5%B8%88%E3%80%81/)、小米、[滴滴](http://www.trinea.cn/android/%E6%BB%B4%E6%BB%B4%E5%87%BA%E8%A1%8C%E5%8C%97%E4%BA%AC%E6%8B%9B%E8%81%98-androidios-%E5%B7%A5%E7%A8%8B%E5%B8%88%E3%80%81%E9%AB%98%E7%BA%A7%E5%B7%A5%E7%A8%8B%E5%B8%88%E3%80%81%E6%9E%B6%E6%9E%84/)、今日头条、知乎、GrowingIO、微店等
上海：[阿里](http://www.trinea.cn/android/%E9%98%BF%E9%87%8C%E9%9B%86%E5%9B%A2%E3%80%81%E8%9A%82%E8%9A%81%E9%87%91%E6%9C%8D%E5%8C%97%E4%B8%8A%E5%B9%BF%E6%B7%B1%E6%9D%AD%E6%8B%9B%E8%81%98-android-ios-%E5%B7%A5%E7%A8%8B%E5%B8%88%E3%80%81/)、腾讯、[蚂蚁金服](http://www.trinea.cn/android/%E9%98%BF%E9%87%8C%E9%9B%86%E5%9B%A2%E3%80%81%E8%9A%82%E8%9A%81%E9%87%91%E6%9C%8D%E5%8C%97%E4%B8%8A%E5%B9%BF%E6%B7%B1%E6%9D%AD%E6%8B%9B%E8%81%98-android-ios-%E5%B7%A5%E7%A8%8B%E5%B8%88%E3%80%81/)、招商银行、饿了么、流利说、即刻、Glow、B 站、拼多多等
杭州：[阿里](http://www.trinea.cn/android/%E9%98%BF%E9%87%8C%E9%9B%86%E5%9B%A2%E3%80%81%E8%9A%82%E8%9A%81%E9%87%91%E6%9C%8D%E5%8C%97%E4%B8%8A%E5%B9%BF%E6%B7%B1%E6%9D%AD%E6%8B%9B%E8%81%98-android-ios-%E5%B7%A5%E7%A8%8B%E5%B8%88%E3%80%81/)、[蚂蚁金服](http://www.trinea.cn/android/%E9%98%BF%E9%87%8C%E9%9B%86%E5%9B%A2%E3%80%81%E8%9A%82%E8%9A%81%E9%87%91%E6%9C%8D%E5%8C%97%E4%B8%8A%E5%B9%BF%E6%B7%B1%E6%9D%AD%E6%8B%9B%E8%81%98-android-ios-%E5%B7%A5%E7%A8%8B%E5%B8%88%E3%80%81/)、微店
深圳：腾讯、[阿里](http://www.trinea.cn/android/%E9%98%BF%E9%87%8C%E9%9B%86%E5%9B%A2%E3%80%81%E8%9A%82%E8%9A%81%E9%87%91%E6%9C%8D%E5%8C%97%E4%B8%8A%E5%B9%BF%E6%B7%B1%E6%9D%AD%E6%8B%9B%E8%81%98-android-ios-%E5%B7%A5%E7%A8%8B%E5%B8%88%E3%80%81/)、[蚂蚁金服](http://www.trinea.cn/android/%E9%98%BF%E9%87%8C%E9%9B%86%E5%9B%A2%E3%80%81%E8%9A%82%E8%9A%81%E9%87%91%E6%9C%8D%E5%8C%97%E4%B8%8A%E5%B9%BF%E6%B7%B1%E6%9D%AD%E6%8B%9B%E8%81%98-android-ios-%E5%B7%A5%E7%A8%8B%E5%B8%88%E3%80%81/)
广州：腾讯、[阿里](http://www.trinea.cn/android/%E9%98%BF%E9%87%8C%E9%9B%86%E5%9B%A2%E3%80%81%E8%9A%82%E8%9A%81%E9%87%91%E6%9C%8D%E5%8C%97%E4%B8%8A%E5%B9%BF%E6%B7%B1%E6%9D%AD%E6%8B%9B%E8%81%98-android-ios-%E5%B7%A5%E7%A8%8B%E5%B8%88%E3%80%81/)

可直接访问 http://j.codekk.com/ 查看具体职位相关信息，每个职位都有详细的工作内容及薪资福利介绍。

**Comment by ervinsae** [comment]
去年面过一次没过，今年能继续吗？。。

**Comment by Trinea** [comment]
@ervinsae 当然
