### ISSUE TITLE
滴滴出行 2018 年北京杭州大量 Android 职位招聘，月 20k-55k，年 16 薪，优秀另有期权

### ISSUE THREAD

**Issue by Trinea** [Trinea/android-open-project#339]
2018 年已接近尾声，我们滴滴一些职位高薪开放。  
  
### **一、主要招聘职位**
前端/Go/Java/Php/C++/算法/Android/iOS/大数据/数分等等职位大量招聘。  
业务包括国际化/后市场/单车/外卖/专车/快车/金融/智慧交通/大数据/地图等。
  
### **二、主要待遇**
① **月 20k-55k，一定级别另有期权**  
② 六险一金，父母及子女的商业保险  
③ 全员 Mac，免费下午茶、免费晚餐  
④ 有孩子或者怀孕的女性员工有每周一天的在家办公机会  
  
### **三、职位描述及要求**
技术岗位主要在北京、杭州、上海。所有职位详情可见： http://talent.didiglobal.com/social/list/1   

### **四、内推方式**
**欢迎简历直接发送到 <trinea.cn@gmail.com>** 或微信联系我([trinea 点击扫码](http://codekk.com/images/weixin-trinea-256.jpeg))内推。 
任何问题或疑惑欢迎留言，有关系好的小伙伴也可以给我们推荐。  
  
![](http://www.trinea.cn/wp-content/uploads/2016/10/mengdian3.jpg)

**Comment by zhu-lingfeng** [comment]
邮件已收到，我会尽快回复~【自动回复】

**Comment by houpe** [comment]
***@***.***

**Comment by hzhzhen** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by itMrc** [comment]
您的邮件小林已收到，谢谢。

**Comment by wzxx** [comment]
您好，已收到邮件，但现在本人还未登陆邮箱，无法马上回复您的邮件。 我将在登陆邮箱后，尽快给您回复，谢谢~

**Comment by zongxiaomi** [comment]
你们都在干什么😂

**Comment by zongxiaomi** [comment]
5年了 大家都还好吗

**Comment by zwzsdy** [comment]
肿么回事

**Comment by YangWanHao** [comment]
啥情况啊&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月14日(星期三) 中午11:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [Trinea/android-open-project] 滴滴出行 2018 年北京杭州大量 Android 职位招聘，月 20k-55k，年 16 薪，优秀另有期权 (#339)





 
肿么回事

**Comment by lelelongwang** [comment]
额，这样真的好么，一下子收到这么多垃圾邮件，取关了

**Comment by hzhzhen** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by wzxx** [comment]
您好，已收到邮件，但现在本人还未登陆邮箱，无法马上回复您的邮件。 我将在登陆邮箱后，尽快给您回复，谢谢~

**Comment by houpe** [comment]
***@***.***

**Comment by itMrc** [comment]
您的邮件小林已收到，谢谢。

**Comment by zhu-lingfeng** [comment]
邮件已收到，我会尽快回复~【自动回复】
