### ISSUE TITLE
页面太长了

### ISSUE THREAD

**Issue by HuarenYu** [Trinea/android-open-project#35]
所有项目都放在一个页面太长了，能不能分开啊。

**Comment by DonLiangGit** [comment]
there's another one called androidarsenal if you find this page too long.

**Comment by lionm117** [comment]
我觉得页面太长 就不是问题， 首先是要有耐心才是关键，欲速则不达，把所有资源集中在一个地方的最大好处就是可以心无旁骛的获取所需资源。 页面太长不是问题，做好分类排版，一眼可以找到所需资源我想才是问题的关键

**Comment by pcqpcq** [comment]
1. 如果页面太长不是问题的话，那么代码分层也没有必要了，因为只要有耐心一行一行的看，总会找到想要的代码在哪里；抽取不同的工具类也没有必要了，因为只要认真一个一个方法去找，即使把所有方法放在一个类里，也总能找到想要的方法在哪里。
2. 现在github的项目内搜索功能，是可以直接搜索项目内的字符的，已经不存在不利于搜索的问题了。
3. 现在ReadMe.md文件已经有2410行，144.433kb了（截止 Mar 30, 2015 ）

**Comment by lionm117** [comment]
> 1 首先阅读代码 和阅读说明书是两个层次上的概念。 说明文档的可读性远高于代码。  真正会阅读完文章的人会很少吧，主要是为了集中下载资源用的，帮助用户最快的找到所需要的资源，并且解释资源基本的信息才是 readme 的 核心责任吧。 所以不相信每次都会需要把readme 通读一遍。 然后采取找资源下载
> 2  既然是为了快速检索， 只要添加一个[TOC] 的标签就行了。如果下载个资源要打开 十多个页面，逐个看，那才叫让人抓狂
> 3 一个文件类两千多行 似乎也不是大的事。 C++ 里面经常的事。
> 4 作为新手，确实需要教程似的分割文章学习。但感觉真的读完一遍，基本上后期就不需要通读了，定点找就行了。 

##个人看法
把下载链接，必要的信息全部放在readme里面，把详细的介绍或者部分图片分离出来，仅提供链接。  可以缩小不必要的信息过载的情况

**Comment by cogbee** [comment]
我觉得图片还是不要去掉，这样能让开发者一下子就知道这个源代码能做的事情，比较形象吧。
放在一页，我觉得内容很丰富啊。

**Comment by woai110120130** [comment]
去掉图片这真是个坏主意

**Comment by liujingyuan1** [comment]
真的不要把图去掉！说的再详细，也没有图文直观吧！

**Comment by qqli007** [comment]
在一个页面没有问题，在页面左边挂一个目录就可以了，可以快速导航

**Comment by pcqpcq** [comment]
很抱歉前面没有思考和表达清楚就发表评论。

@lionm117 我同意你的大部分观点，并且我觉得大家会有不同观点主要是因为这个问题：
> 这个项目的目标定位是作为一个集合还是作为一个索引？

这个问题的答案应该每个人看法都不一样，理论上应该是由作者@Trinea 决定。

------

从我的角度来说，我认为它是：
> 作为一个索引

我对于项目中已有的大部分资源已经熟悉，所以在一个页面中显示我已经了解的东西对我而言可能是多余的，因此我才会更倾向于把当前的ReadMe拆分开，通过 `目录索引/项目搜索` 来指向我需要的东西即可。  
我想@ HuarenYu 提这个Issue以及其他有类似想法的人应该也是这个观点吧？  
我觉得你说的 `“但感觉真的读完一遍，基本上后期就不需要通读了，定点找就行了。”` 也是想表达这个意思吧？

------

以上只是我的个人观点。
至于解决办法，Github的目标就不是用来做这类事情的（不论是集合或是索引），它更适合于作代码浏览，也许另外建站会有更好的展示方案。

------

定位是个不好把握并且不同人有不同观点的事情，希望可以多讨论交流。:smile:  
  
另外，我提到的项目内搜索指的页面顶部的搜索框，而不是Ctrl+F：
![](http://i.imgur.com/8I4pfxS.jpg)

**Comment by Trinea** [comment]
Hi, All:

不一一 at 了，页面太长，确实是很大的问题，加上图片加载后扩张页面，造成体验很差。

#### 1. 项目汇总后续计划
这个问题之前已经有了初步的想法，也跟 @pcqpcq  @rengwuxian  等一些朋友简单沟通过，后续这个项目会跟 [codekk.com](http://www.codekk.com/) 网站结合在一起。

另跟 [源码解析第一期](http://weibo.com/1714487171/C2y6LelP1?from=page_1005051714487171_profile&wvr=6&mod=weibotime) 发布时提到的想法一致，还会跟源码解析的文章关联到一起。

暂时抽不出时间，大概在 5 月中会初步完成，之后也会有更多扩展，整体争取在上半年全部完成。

#### 2. 本页面后续计划
至于这个页面在完成了上面的想法后怎么修改已经不那么重要，具体到时根据需要调整。

总之这个项目会朝着更好的方向发展，感谢大家关注，后续需要的时候我们也会收集大家对改版的意见:smile:

**Comment by xu6148152** [comment]
做成像Arsenal就好了。

**Comment by imknown** [comment]
要是能 启用 Github Pages, 在 HTML 里面 规划规划  页面跳转 就好了, 公司这个 烂网速, 打开暴慢

**Comment by whinc** [comment]
觉得页面过长的看来不止我一个啊，哈啊哈 ~ ~

**Comment by zhuiji7** [comment]
确实越来越长了，还没考虑做分页么~
