### ISSUE TITLE
Android 开源交流 QQ 群 6 个群已满，不会再有新群。

### ISSUE THREAD

**Issue by Trinea** [Trinea/android-open-project#52]
Android 开源交流 QQ 群 6 个群已满，不会再有新群。  

Gitter Chat Room，大家有兴趣可以加下： https://gitter.im/Trinea/android-open-project?utm_source=share-link&utm_medium=link&utm_campaign=share-link  

> 欢迎加入 QQ 交流群：[383537512(入群理由必须填写群简介问题答案)](http://shang.qq.com/wpa/qunwpa?idkey=69b7c4278fc3a33690d4847ed7f9a72b9e4feb51221265a7326cf5261ccd5862 "入群理由必须填写群简介问题答案")(二群有空位)  
注意：入群理由必须填写群简介问题答案(Mac 点击群头像查看)。  

> [377723625](http://shang.qq.com/wpa/qunwpa?idkey=12ba39b0c3f5d27620ab0cb63ff80507a8a30fd743a11fad028e7742a871e0dc "入群理由必须填写群简介问题答案")(一群已满) [63224677](http://shang.qq.com/wpa/qunwpa?idkey=fb2eaf0c4b4a8c838ad15e6bdd69d901f038a50f4a77360845b9e6d7ee0ba3ee "入群理由必须填写群简介问题答案")(三群已满) [148844489](http://shang.qq.com/wpa/qunwpa?idkey=5dc2f22b2f9fe3b6136f9cad29399713b118bfaa9a2330e410757362a37572bc "入群理由必须填写群简介问题答案")(四群已满) [214742675](http://jq.qq.com/?_wv=1027&k=Zl6Yyj "入群理由必须填写群简介问题答案")(五群已满) [185715999](http://jq.qq.com/?_wv=1027&k=fJlrh1 "入群理由必须填写群简介问题答案")(六群已满) 请不要重复加群  

<p>&nbsp;</p>
目前几个群的公告都是： 欢迎技术交流，拒绝伸手党！Google 前两页有答案的提问，没有思考的追问，无聊的扯淡都会被踢！  
<p>&nbsp;</p>
这些群的另外一个目的也是为了 [Android优秀开源项目实现原理解析](https://github.com/android-cn/android-open-project-analysis) 这个项目的初期审稿，因为时间原因，这个项目暂时被 Delay  
<p>&nbsp;</p>

讨论请大家移步 [关于 Android 开源 QQ 群规则](http://www.trinea.cn/plan-summary/android-communication-qq-group-rule/) ，不要在这里回复，以免邮件通知影响这个项目的几千关注者

**Comment by dongeast** [comment]
http://www.trinea.cn/android/android-plugin/ 你的网站挂掉了？

**Comment by Trinea** [comment]
@dongeast 这几天服务器不稳定... 周末弄下

**Comment by yan96in** [comment]
可以更改加群设置吗 我想进群瞅瞅

**Comment by htrim87** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

htrim87@naver.com 님께 보내신 메일 <Re: [android-open-project] Android 开源交流 QQ 群 6 个群已满，不会再有新群。 (#52)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
