### ISSUE TITLE
【警告】你以为你是谁？开源项目是全世界的开发者贡献的，你还敢说别人是伸手党？

### ISSUE THREAD

**Issue by ghost** [Trinea/android-open-project#53]
你以为你是谁？开源项目是全世界的开发者贡献的，还伸手党？我这么跟你说，我加过你的群了，也都被你三个群都踢出来过，你绝对不是为了贡献而做技术的，而是为了你那卑微而可怜的控制欲和装逼欲。你以为你是谁？国家领导人？架子好大哟，说一两句话就被踢，别人不知道怎么回事呢就被你T了。你是神仙？你说别人是伸手党了别人拿你什么了？难道你就不是伸手党了？你还不是拿来全世界的开发者点缀你那个可怜巴巴的Github主页和博客主页。真不知道你是被谁给惯出来这么些坏毛病。好像你认同的高手就是高手，别人谦虚一下就不是高手了？我告诉你，你就是一个无耻之徒，技术盗窃犯！你这种瞧不起别人的人就应该像我这样发几篇这样的帖子打打巴掌！被人批评被人唾弃你是活该！

**Comment by mox1103** [comment]
既然自己都说每个人都有自由 ... 人家的群... 想踢你是人家的自由

**Comment by renhuihhh** [comment]
这位炮嘴哥好愤青  我这么说吧，作为大学毕业三年自学编程 自学android 整天谷歌 整天github的我都觉得不够资格加入trinea的群，我都是默默的一直在关注  一直在学习，做人要谦虚  凡事从自身找问题，我相信trinea的前辈们不会没有原则而踢你出群的

**Comment by TakWolf** [comment]
别TMD撕逼，烦死了

**Comment by stormzhang** [comment]
说这么多干嘛，对于这种愤青我一般回复：就T你了，咋的？！

**Comment by qiuxiaoj** [comment]
尼玛，对于这种伸手党、嘴炮逼。我想说：踢500次也不会多。

2015-06-29 20:19 GMT+08:00 stormzhang <notifications@github.com>:

**Comment by H273** [comment]
在 GitHub 上群喷也是醉了，Unstar、Unwatch，眼不见心不烦

**Comment by kenanconan** [comment]
这种脑残群加进去又有什么用啊，说得好像自己很牛逼一样，拿着国外写的东西在那共享，还逼逼说得条条有理，我想说一句，去你吗个逼的

**Comment by Hellobird** [comment]
Unstar、Unwatch，都是些喷子，也没什么意思了。

**Comment by linchangjian** [comment]
...

**Comment by lionm117** [comment]
english only , everything would be clean . no bullshit would be  recieved in my email . 
no contribution , no right to criticize .

**Comment by cnzx219** [comment]
unwatch

**Comment by noprom** [comment]
Unwatch,don't send me it again.
